homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods: [GET]  

api_test:
    path:     /test
    defaults: { _controller: AppBundle:Default:totalsCacluator }
    methods: [POST]   
